version: '3'
services:
  logdbpostgres:
    image: postgres:14.0
    container_name: logdbpostgres
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
